### ISSUE TITLE
Login page background does not cover whole screen on large resolution screens

### ISSUE THREAD

**Issue by beichenc** [beichenc/MusicMap#18]
Occurs when testing on dad's computer.

**Comment by mictab** [comment]
☝️ One of the most common testing methods in software engineering.

**Comment by beichenc** [comment]
Lolol @mictab, not entirely sure how to test resolution problems - the simulator on my Macbook only goes so far. The background is fine even on the highest res when I use the simulator. However, my father's computer (Dell XPS 13) has a really messed up resolution that screws up our iprogd project as well as this one :P

**Comment by beichenc** [comment]
Fixed by adding background-size: 100% on computers, and removing background image for mobile and tablets.
