### ISSUE TITLE
add cookies?

### ISSUE THREAD

**Issue by amyychen** [beichenc/MusicMap#25]
Adding cookies for log in status for users, so the users skip the log in page and go directly to the home page, when they enter the website again. We need to check if this will work with the access token.

**Comment by amyychen** [comment]
Have a thought about if we can save the refresh token to cookies. Then check it the user has cookies when the user enter the website. If does, get the access token for the user and skip the log in page. If doesn't, go to the login page.

**Comment by beichenc** [comment]
Added refresh token to cookies. Now when the user goes to login page they are directed to home page without having to log in, if they have logged in previously. 

We need to add logout as well.

**Comment by amyychen** [comment]
added log out page so it clears the cookies on our database when clicking on it. Users will then be directed to the login/home page.
