### ISSUE TITLE
Refactor filters code

### ISSUE THREAD

**Issue by beichenc** [beichenc/MusicMap#41]
Feels like I have repeated myself... there must be a better way to filter (think of what if there were like 10 different filters that can be applied in a combined manner).

Maybe we don't need to fix this yet as we are switching to Ruby on Rails anyway.

**Comment by beichenc** [comment]
We should refactor the filters code so that we can query the backend instead of obtaining all mapped songs and then filtering in the frontend. For example, if we want all pop music we should send "pop" as a query to the backend and make the backend filter out all entries whose genres contain "pop", and return only those in the JSON.

**Comment by amyychen** [comment]
We moved the database from firebase to our own backend on heroku. It makes that we could refactor the filters to filter in the backend before sending back the data. We did also add an user filter to find mapped songs by a specific username. We also changed the search function/button to search for all filters when clicking on it. This filter issue is done.
