### ISSUE TITLE
Feature 6 - Filter by genre

### ISSUE THREAD

**Issue by amyychen** [beichenc/MusicMap#6]
Filter by genre (pop, blues, jazz etc.) and the map will only displaying the songs that were previously marked there with the matched genre in the current/chosen location. Users will search for a specific genre in the searching bar, then choose one of the matching results.

**Comment by beichenc** [comment]
<img width="1253" alt="screen shot 2017-04-17 at 14 09 49" src="https://cloud.githubusercontent.com/assets/24257753/25088827/b61ad196-2379-11e7-8ec4-4626dc679d08.png">

The filter search will be located in the sidebar that appears when user clicks "more".

**Comment by amyychen** [comment]
done
