### ISSUE TITLE
Enhancement 1 - Backend

### ISSUE THREAD

**Issue by amyychen** [beichenc/MusicMap#8]
If we have time enough, we will try implement a backend for the data using Ruby on Rails.

**Comment by beichenc** [comment]
Built backend models: mapped_songs, and users. Moved our mapped songs data from Firebase to our backend hosted on Heroku: https://bestmusicmapapi.herokuapp.com . 

Next: implement the users model by saving data to it every time a completely new user logs in.

**Comment by beichenc** [comment]
Created a repository for the backend, here: https://github.com/beichenc/MusicMapAPI

**Comment by beichenc** [comment]
We have now finished implementing the users model.

Any future additions to the backend will be handled in the backend repository.
